accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup', views.SignUpView.as_view(), name='signup'),
]

posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<str:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

social_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups', include('groups.urls', namespace='groups'))
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Star Social</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="{% static 'social_project/css/master.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'posts:create' %}">Post</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'groups:all' %}">Groups</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'groups:create' %}">Create Group</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'groups:all' %}">Groups</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'accounts:login' %}">Log In</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mycontent">
            {% block content %}
            {% endblock %}
        <canvas id="canvas"></canvas>
    </div>
</body>
<script type="text/javascript" src="{% static 'social_project/js/master.js' %}"></script>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome to Star Social!</h1>

{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block content %}

<h1>You are now logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}

<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}